### ISSUE TITLE
Padding handling compared to OAI's codebase

### ISSUE THREAD

**Issue by vwxyzjn** [lvwerra/trl#469] opened 2023-06-26 15:57 UTC
It seems there is a discrepancy in padding handling compared to OAI's codebase, which could be related to https://github.com/lvwerra/trl/pull/423 https://github.com/lvwerra/trl/issues/355 https://github.com/lvwerra/trl/issues/235

Consider a simple query of a single word `query=[23073,]` and a response of `[837,   339,   561]`, I compare the logits generated by different strategies as well as the output of the original codebase.

Repro script: https://gist.github.com/vwxyzjn/811c2cb6c7387bda25fb47c8e4c6867f

## Ground truth

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
from trl import AutoModelForCausalLMWithValueHead, PPOConfig, PPOTrainer
tokenizer = AutoTokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token
pad_id = tokenizer.pad_token_id
pretrained_model = AutoModelForCausalLM.from_pretrained("gpt2")
print("no padding")
oai_example_query_response = [[23073,  837,   339,   561]]
output = pretrained_model(
    input_ids=torch.tensor(oai_example_query_response),
    return_dict=True,
    output_hidden_states=True,
)
print(output.logits)
```
```bash
no padding
tensor([[[ -35.2869,  -34.2875,  -38.1608,  ...,  -41.5958,  -41.0821,
           -35.3658],
         [ -80.0448,  -78.7162,  -79.4811,  ...,  -85.6632,  -84.4848,
           -79.3501],
         [ -99.9618,  -98.6820, -102.0919,  ..., -107.7490, -100.2977,
          -100.8713],
         [-117.9464, -117.6599, -123.0824,  ..., -127.6637, -125.5362,
          -120.7827]]], grad_fn=<UnsafeViewBackward0>)
````

The output is identical to OAI's codebase ([vwxyzjn/lm-human-preferences/a1.py#L105-L106](https://github.com/vwxyzjn/lm-human-preferences/blob/6b4caa7d3d797edda9f857b329699b1733451394/a1.py#L105-L106))

<img width="1260" alt="image" src="https://github.com/lvwerra/trl/assets/5555347/53a76a5d-cb81-44b9-9596-261893ccac4d">

For RLHF purposes to calculate the logprob and ratio, we can just take a look at if the following logits can be reproduced.

` [ -99.9618,  -98.6820, -102.0919,  ..., -107.7490, -100.2977,
          -100.8713],`

## Deal with padding in OAI.

OAI operates with right padding, so the input to the model is 

```
queries = np.array([[23073, 50259, 50259]])
responses = np.array([[837,   339,   561]])
```

<img width="1229" alt="image" src="https://github.com/lvwerra/trl/assets/5555347/539e4ee5-926f-451b-bb5f-4f85fa642c4e">

Note that there are two interesting things: 

1. **the logits remained the same for the first three outputs** because the second and third tokens are padding tokens.
2. **the final logits and entropy is the same** (when doing RLHF we will be only look at logits until ` [ -99.9618,  -98.6820, -102.0919,  ..., -107.7490, -100.2977, -100.8713],`)

## Deal with padding in Transformer

When using `.forward()` or `__call__()` with transformers, note that, however, the `logits` are not preserved when encountering padding tokens!

```
print("right padding")
oai_example_query_response = [[23073, pad_id, pad_id, 837,   339,   561]]
output = pretrained_model(
    input_ids=torch.tensor(oai_example_query_response),
    attention_mask=torch.tensor([[1, 0, 0, 1, 1, 1]]),
    return_dict=True,
    output_hidden_states=True,
)
print(output.logits)
```
```
right padding
tensor([[[ -35.2869,  -34.2875,  -38.1608,  ...,  -41.5958,  -41.0821,
           -35.3658],
         [ -59.9964,  -56.1110,  -61.1633,  ...,  -67.5749,  -66.9844,
           -58.7757],
         [ -63.4215,  -59.0773,  -64.1116,  ...,  -71.4769,  -70.4776,
           -61.8506],
         [ -60.4824,  -59.5069,  -59.0145,  ...,  -65.7242,  -64.9456,
           -57.6964],
         [ -96.7052,  -95.2847,  -98.7656,  ..., -104.2707,  -96.1588,
           -97.0177],
         [-118.6185, -118.3233, -123.9547,  ..., -128.3873, -125.9578,
          -121.3531]]], grad_fn=<UnsafeViewBackward0>)
```

When using the left padding, the logits ` [ -99.9618,  -98.6820, -102.0919,  ..., -107.7490, -100.2977, -100.8713],` are no longer recoverable. It is unclear whether this would have performance implications.

```
print("left padding")
oai_example_query_response = [[pad_id, pad_id, 23073, 837,   339,   561]]
output = pretrained_model(
    input_ids=torch.tensor(oai_example_query_response),
    attention_mask=torch.tensor([[0, 0, 1, 1, 1, 1]]),
    return_dict=True,
    output_hidden_states=True,
)
print(output.logits)
```
```
left padding
tensor([[[ -18.5070,  -17.4824,  -20.6231,  ...,  -25.8483,  -25.5320,
           -18.2190],
         [ -64.4989,  -59.9864,  -66.1932,  ...,  -75.1809,  -74.4133,
           -65.0254],
         [ -64.5949,  -58.6015,  -60.2131,  ...,  -73.3745,  -69.8167,
           -62.4603],
         [-114.0506, -113.2478, -116.2816,  ..., -128.3271, -128.4225,
          -113.5495],
         [-110.9634, -109.1507, -115.5589,  ..., -126.3668, -125.3111,
          -113.9162],
         [-157.7421, -154.7699, -161.9627,  ..., -171.2903, -173.3014,
          -159.7751]]], grad_fn=<UnsafeViewBackward0>)
```

## Deal with padding in TRL

When using the `batched_forward_pass` without the padding, the output checks out the same, meaning we can recover ` [ -99.9618,  -98.6820, -102.0919,  ..., -107.7490, -100.2977, -100.8713],`
```
print("batched_forward_pass")
model = AutoModelForCausalLMWithValueHead.from_pretrained("gpt2")
model_ref = AutoModelForCausalLMWithValueHead.from_pretrained("gpt2")
batch_size = 1
ppo_config = PPOConfig(
    batch_size=batch_size,
    learning_rate=1.41e-5,
    mini_batch_size=1,
)
ppo_trainer = PPOTrainer(ppo_config, model, model_ref, tokenizer)
oai_example_query = [[23073,   ]]
oai_example_response = [[837,   339,   561]]
model_inputs = ppo_trainer.prepare_model_inputs(
    torch.tensor(oai_example_query), 
    torch.tensor(oai_example_response)
)
all_logprobs, logits, _, _ = ppo_trainer.batched_forward_pass(
    model,
    torch.tensor(oai_example_query), 
    torch.tensor(oai_example_response),
    model_inputs=model_inputs,
    return_logits=True,
)
print(logits)
```
```
batched_forward_pass
tensor([[[ -35.2869,  -34.2875,  -38.1608,  ...,  -41.5958,  -41.0821,
           -35.3658],
         [ -80.0448,  -78.7162,  -79.4811,  ...,  -85.6632,  -84.4848,
           -79.3501],
         [ -99.9618,  -98.6820, -102.0919,  ..., -107.7490, -100.2977,
          -100.8713]]], grad_fn=<SliceBackward0>)
```

However, it suffers the same issue with transformer's forward with right padding, `` [ -99.9618,  -98.6820, -102.0919,  ..., -107.7490, -100.2977, -100.8713],` is no longer recoverable. 
```
print("batched_forward_pass w/ right padding")
model = AutoModelForCausalLMWithValueHead.from_pretrained("gpt2")
model_ref = AutoModelForCausalLMWithValueHead.from_pretrained("gpt2")
batch_size = 1
ppo_config = PPOConfig(
    batch_size=batch_size,
    learning_rate=1.41e-5,
    mini_batch_size=1,
)
ppo_trainer = PPOTrainer(ppo_config, model, model_ref, tokenizer)
oai_example_query = [[23073,   ]]
oai_example_response = [[837,   339,   561]]
model_inputs = {
    "input_ids": torch.tensor([[23073, pad_id, pad_id, 837,   339,   561]]),
    "attention_mask": torch.tensor([[1, 0, 0, 1, 1, 1]]),
}
all_logprobs, logits, _, _ = ppo_trainer.batched_forward_pass(
    model,
    torch.tensor(oai_example_query), 
    torch.tensor(oai_example_response),
    model_inputs=model_inputs,
    return_logits=True,
)
print(logits)
```
```
batched_forward_pass w/ right padding
tensor([[[ -35.2869,  -34.2875,  -38.1608,  ...,  -41.5958,  -41.0821,
           -35.3658],
         [ -59.9964,  -56.1110,  -61.1633,  ...,  -67.5749,  -66.9844,
           -58.7757],
         [ -63.4215,  -59.0773,  -64.1116,  ...,  -71.4769,  -70.4776,
           -61.8506],
         [ -60.4824,  -59.5069,  -59.0145,  ...,  -65.7242,  -64.9456,
           -57.6964],
         [ -96.7052,  -95.2847,  -98.7656,  ..., -104.2707,  -96.1588,
           -97.0177]]], grad_fn=<SliceBackward0>)
```
Similar issue with the left padding. 
```
print("batched_forward_pass w/ left padding")
model = AutoModelForCausalLMWithValueHead.from_pretrained("gpt2")
model_ref = AutoModelForCausalLMWithValueHead.from_pretrained("gpt2")
batch_size = 1
ppo_config = PPOConfig(
    batch_size=batch_size,
    learning_rate=1.41e-5,
    mini_batch_size=1,
)
ppo_trainer = PPOTrainer(ppo_config, model, model_ref, tokenizer)
oai_example_query = [[23073,   ]]
oai_example_response = [[837,   339,   561]]
model_inputs = {
    "input_ids": torch.tensor([[pad_id, pad_id, 23073, 837,   339,   561]]),
    "attention_mask": torch.tensor([[0, 0, 1, 1, 1, 1]]),
}
all_logprobs, logits, _, _ = ppo_trainer.batched_forward_pass(
    model,
    torch.tensor(oai_example_query), 
    torch.tensor(oai_example_response),
    model_inputs=model_inputs,
    return_logits=True,
)
print(logits)
```

```
batched_forward_pass w/ left padding
tensor([[[ -18.5070,  -17.4824,  -20.6231,  ...,  -25.8483,  -25.5320,
           -18.2190],
         [ -64.4989,  -59.9864,  -66.1932,  ...,  -75.1809,  -74.4133,
           -65.0254],
         [ -64.5949,  -58.6015,  -60.2131,  ...,  -73.3745,  -69.8167,
           -62.4603],
         [-114.0506, -113.2478, -116.2816,  ..., -128.3271, -128.4225,
          -113.5495],
         [-110.9634, -109.1507, -115.5589,  ..., -126.3668, -125.3111,
          -113.9162]]], grad_fn=<SliceBackward0>)
```

**Comment by maxreciprocate** [comment] 2023-06-26 20:43
This discrepancy should be fixed with adding `position_ids`, because `attention_mask` is ignored in https://github.com/huggingface/transformers/blame/main/src/transformers/models/gpt2/modeling_gpt2.py#L805 
```python
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
tokenizer = AutoTokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token
pad_id = tokenizer.pad_token_id
pretrained_model = AutoModelForCausalLM.from_pretrained("gpt2")
print("no padding")
oai_example_query_response = [[23073,  837,   339,   561]]
output_no_padding = pretrained_model(
    input_ids=torch.tensor(oai_example_query_response),
    return_dict=True,
    output_hidden_states=True,
)
print(output_no_padding.logits)

print("left padding (no position_ids)")
oai_example_query_response = [[pad_id, pad_id, 23073, 837,   339,   561]]
output_left_padding = pretrained_model(
    input_ids=torch.tensor(oai_example_query_response),
    attention_mask=torch.tensor([[0, 0, 1, 1, 1, 1]]),
    return_dict=True,
    output_hidden_states=True,
)
print(output_left_padding.logits)

print("left padding (with position_ids)")
oai_example_query_response = [[pad_id, pad_id, 23073, 837,   339,   561]]
output_left_padding_with_position_ids = pretrained_model(
    input_ids=torch.tensor(oai_example_query_response),
    attention_mask=torch.tensor([[0, 0, 1, 1, 1, 1]]),
    position_ids=torch.tensor([[0, 0, 0, 1, 2, 3]]),
    return_dict=True,
    output_hidden_states=True,
)
print(output_left_padding_with_position_ids.logits)

torch.testing.assert_close(output_left_padding_with_position_ids.logits[:, 2:, :], output_no_padding.logits)
```

Output:
```
no padding
position_ids=None
position_ids=tensor([[0, 1, 2, 3]])
tensor([[[ -35.2869,  -34.2875,  -38.1608,  ...,  -41.5958,  -41.0821,
           -35.3658],
         [ -80.0448,  -78.7162,  -79.4811,  ...,  -85.6633,  -84.4848,
           -79.3501],
         [ -99.9618,  -98.6820, -102.0919,  ..., -107.7490, -100.2977,
          -100.8713],
         [-117.9465, -117.6599, -123.0824,  ..., -127.6638, -125.5362,
          -120.7827]]], grad_fn=<UnsafeViewBackward0>)
left padding (no position_ids)
position_ids=None
position_ids=tensor([[0, 1, 2, 3, 4, 5]])
tensor([[[ -18.5070,  -17.4824,  -20.6230,  ...,  -25.8483,  -25.5320,
           -18.2190],
         [ -64.4989,  -59.9864,  -66.1931,  ...,  -75.1809,  -74.4132,
           -65.0253],
         [ -64.5948,  -58.6014,  -60.2131,  ...,  -73.3745,  -69.8167,
           -62.4603],
         [-114.0500, -113.2472, -116.2810,  ..., -128.3264, -128.4218,
          -113.5488],
         [-110.9633, -109.1506, -115.5588,  ..., -126.3666, -125.3110,
          -113.9161],
         [-157.7403, -154.7681, -161.9608,  ..., -171.2885, -173.2995,
          -159.7733]]], grad_fn=<UnsafeViewBackward0>)
left padding (with position_ids)
position_ids=tensor([[0, 0, 0, 1, 2, 3]])
tensor([[[ -24.9804,  -24.1358,  -27.3116,  ...,  -31.2592,  -31.0166,
           -24.8214],
         [ -25.2744,  -24.3320,  -27.5048,  ...,  -31.7700,  -31.5194,
           -25.0381],
         [ -35.2869,  -34.2875,  -38.1608,  ...,  -41.5958,  -41.0821,
           -35.3658],
         [ -80.0448,  -78.7162,  -79.4810,  ...,  -85.6633,  -84.4848,
           -79.3501],
         [ -99.9617,  -98.6820, -102.0919,  ..., -107.7490, -100.2977,
          -100.8713],
         [-117.9464, -117.6599, -123.0824,  ..., -127.6638, -125.5362,
          -120.7827]]], grad_fn=<UnsafeViewBackward0>)
```

**Comment by timonziegenbein** [comment] 2023-06-27 14:55
Interesting discussion! 
However, I do not see a problem with the current implementation except for the cutoff of the last token. 

Currently, `prepare_model_inputs` simply concatenates the queries and responses. The padding is done afterward on batch level. This should preserve the position embeddings.

Interestingly `batched_forward_pass` cuts off the last logits of the last token, which leads to @vwxyzjn 'Dealing with padding in TRL' example. If I modify the `batched_forward_pass` to not cut off the last token, I can reproduce the logits.

Here is the snippet I used:

```
from transformers import AutoTokenizer, AutoModelForCausalLM
from trl import PPOTrainer, PPOConfig, AutoModelForCausalLMWithValueHead
from trl.models import PreTrainedModelWrapper
from trl.trainer.ppo_trainer import logprobs_from_logits
import torch

class CustomPPOTrainer(PPOTrainer):
    def batched_forward_pass(
        self,
        model: PreTrainedModelWrapper,
        queries: torch.Tensor,
        responses: torch.Tensor,
        model_inputs: dict,
        return_logits: bool = False,
    ):
        bs = len(queries)
        fbs = self.config.mini_batch_size
        all_logprobs = []
        all_logits = []
        all_masks = []
        all_values = []

        for i in range(int(bs / fbs)):
            input_kwargs = {key: value[i * fbs : (i + 1) * fbs] for key, value in model_inputs.items()}
            query_batch = queries[i * fbs : (i + 1) * fbs]
            response_batch = responses[i * fbs : (i + 1) * fbs]
            logits, _, values = model(**input_kwargs)

            if self.is_encoder_decoder:
                input_ids = input_kwargs["decoder_input_ids"]
                attention_mask = input_kwargs["decoder_attention_mask"]
            else:
                input_ids = input_kwargs["input_ids"]
                attention_mask = input_kwargs["attention_mask"]

            logprobs = logprobs_from_logits(logits, input_ids)
            masks = torch.zeros_like(attention_mask)
            masks = attention_mask

            for j in range(fbs):
                if self.is_encoder_decoder:
                    # Decoder sentence starts always in the index 1 after padding in the Enc-Dec Models
                    start = 1
                    end = attention_mask[j, :].sum() - 1
                else:
                    start = len(query_batch[j]) - 1
                    if attention_mask[j, 0] == 0:  # offset left padding
                        start += attention_mask[j, :].nonzero()[0]
                    end = start + len(response_batch[j])

                if len(logprobs[j, start:end]) < 2:
                    raise ValueError("Responses are too short. Make sure they are at least 4 tokens long.")

                masks[j, :start] = 0
                masks[j, end:] = 0

            if return_logits:
                all_logits.append(logits)
            else:
                del logits
            all_values.append(values)
            all_logprobs.append(logprobs)
            all_masks.append(masks)

        return (
            torch.cat(all_logprobs),
            torch.cat(all_logits)if return_logits else None,
            torch.cat(all_values),
            torch.cat(all_masks),
        )
```

```
tokenizer = AutoTokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token
pad_id = tokenizer.pad_token_id
model = AutoModelForCausalLMWithValueHead.from_pretrained("gpt2")
model_ref = AutoModelForCausalLMWithValueHead.from_pretrained("gpt2")
batch_size = 1
ppo_config = PPOConfig(
    batch_size=batch_size,
    learning_rate=1.41e-5,
    mini_batch_size=1,
)
ppo_trainer = CustomPPOTrainer(ppo_config, model, model_ref, tokenizer)
oai_example_query = [[23073,   ]]
oai_example_response = [[837,   339,   561]]
model_inputs = ppo_trainer.prepare_model_inputs(
    torch.tensor(oai_example_query), 
    torch.tensor(oai_example_response)
)
print(model_inputs)
all_logprobs, logits, _, _ = ppo_trainer.batched_forward_pass(
    model,
    torch.tensor(oai_example_query), 
    torch.tensor(oai_example_response),
    model_inputs=model_inputs,
    return_logits=True,
)
print(logits)`
```

Which returns 
![image](https://github.com/lvwerra/trl/assets/29230306/fb1c9d8d-e9bc-4d96-8944-fe424af2892d)

Maybe @lvwerra knows why this cut off happens?

**Comment by lvwerra** [comment] 2023-07-05 08:40
Hi there y'all! Thanks for the thorough analysis! 

> Maybe @lvwerra knows why this cut off happens?

The reason we cutoff the last logit is that it corresponds to a token that hasn't been generated (the first token after the response). This is because input ids and logits are offset by 1: the n-first tokens predict the logit of the n+1 token.

**Closed** 2023-08-06 15:05 UTC
