### ISSUE TITLE
DPO Trainer Support for Seq2SeqLM

### ISSUE THREAD

**Issue by Vasanthengineer4949** [lvwerra/trl#626] opened 2023-08-09 02:00 UTC
DPO Trainer seems to be great replacement for RLHF based training. Would like to experiment with FlanT5 or such seq2seq architectures. A support for those would be great

**Comment by lvwerra** [comment] 2023-08-09 10:14
This is a duplicate of #579 and should be addressed in #586. Thus closing this in favour of the other issue.

**Closed by lvwerra** 2023-08-09 10:14 UTC
