### ISSUE TITLE
About gpt2-sentiment.py

### ISSUE THREAD

**Issue by YTL7** [lvwerra/trl#183] opened 2023-03-01 09:57 UTC
Can you run this project(examples/sentiment/scripts/gpt2-sentiment.py) successfully? Why do I have many bugs[TypeError: new(): invalid data type 'str']

**Comment by younesbelkada** [comment] 2023-03-01 09:59
Hello @Ytlskys 
Can you share with us more details about your environment? What is the command you are using?
Thanks!

**Comment by Ytlskys** [comment] 2023-03-01 14:47
Thank you for your attention！
datasets=2.0.0  torch= 1.12.1+cu116  tqdm=4.64.1  transformers= 4.26.1accelerate=0.16.0
Traceback (most recent call last):
  File "D:\Python\Test\test\T\trl-main\examples\sentiment\scripts\gpt2-sentiment.py", line 135, in <module>
    for epoch, batch in tqdm(enumerate(ppo_trainer.dataloader)):
  File "E:\Python\python3.10.5\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "E:\Python\python3.10.5\lib\site-packages\accelerate\data_loader.py", line 378, in __iter__
    current_batch = next(dataloader_iter)
  File "E:\Python\python3.10.5\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "E:\Python\python3.10.5\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "E:\Python\python3.10.5\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Python\python3.10.5\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Python\python3.10.5\lib\site-packages\datasets\arrow_dataset.py", line 1765, in __getitem__
    return self._getitem(
  File "E:\Python\python3.10.5\lib\site-packages\datasets\arrow_dataset.py", line 1750, in _getitem
    formatted_output = format_table(
  File "E:\Python\python3.10.5\lib\site-packages\datasets\formatting\formatting.py", line 532, in format_table
    return formatter(pa_table, query_type=query_type)
  File "E:\Python\python3.10.5\lib\site-packages\datasets\formatting\formatting.py", line 281, in __call__
    return self.format_row(pa_table)
  File "E:\Python\python3.10.5\lib\site-packages\datasets\formatting\torch_formatter.py", line 58, in format_row
    return self.recursive_tensorize(row)
  File "E:\Python\python3.10.5\lib\site-packages\datasets\formatting\torch_formatter.py", line 54, in recursive_tensorize
    return map_nested(self._recursive_tensorize, data_struct, map_list=False)
  File "E:\Python\python3.10.5\lib\site-packages\datasets\utils\py_utils.py", line 314, in map_nested
    mapped = [
  File "E:\Python\python3.10.5\lib\site-packages\datasets\utils\py_utils.py", line 315, in <listcomp>
    _single_map_nested((function, obj, types, None, True, None))
  File "E:\Python\python3.10.5\lib\site-packages\datasets\utils\py_utils.py", line 251, in _single_map_nested
    return function(data_struct)
  File "E:\Python\python3.10.5\lib\site-packages\datasets\formatting\torch_formatter.py", line 51, in _recursive_tensorize
    return self._tensorize(data_struct)
  File "E:\Python\python3.10.5\lib\site-packages\datasets\formatting\torch_formatter.py", line 43, in _tensorize
    return torch.tensor(value, **{**default_dtype, **self.torch_tensor_kwargs})
TypeError: new(): invalid data type 'numpy.str_'
I'm sorry i do not  know how to solve it

**Comment by Ren-Ma** [comment] 2023-03-02 03:39
I got the same issue when the code `for epoch, batch in tqdm(enumerate(ppo_trainer.dataloader)):` was executed. Google told me that some columns in the dataset are strings instead of numbers might be the reason. So I commented out `sample["query"] = tokenizer.decode(sample["input_ids"])` in the `build_dataset()` function, then added this line of code `batch["query"] = [tokenizer.decode(q.squeeze()) for q in batch["input_ids"]]` after `batch["response"] = [tokenizer.decode(r.squeeze()) for r in response_tensors]`. In this way, the error disappeared and we can still get "query" without using dataset/dataloader. 
Hope this helps!

**Comment by dengyuning** [comment] 2023-03-02 03:50
> I got the same issue when the code `for epoch, batch in tqdm(enumerate(ppo_trainer.dataloader)):` was executed. Google told me that some columns in the dataset are strings instead of numbers might be the reason. So I commented out `sample["query"] = tokenizer.decode(sample["input_ids"])` in the `build_dataset()` function, then added this line of code `batch["query"] = [tokenizer.decode(q.squeeze()) for q in batch["input_ids"]]` after `batch["response"] = [tokenizer.decode(r.squeeze()) for r in response_tensors]`. In this way, the error disappeared and we can still get "query" without using dataset/dataloader. Hope this helps!

What is your environment? I met another issue here : 
![image](https://user-images.githubusercontent.com/23352752/222326556-03e53011-ae47-46d2-a3a3-ff5d3fea990c.png)

**Comment by Ren-Ma** [comment] 2023-03-02 07:28
@dengyuning this seems not like an environment issue ... One guess is that you have inconsistent dimensions between `advantages` and `mask` when you execute `advantages = masked_whiten(advantages, mask)` in line 767 in ppo_trainer.py. I would suggest you to open debug mode, step into this file, run to line 767, and check the shapes of `advantages` and `mask`.

**Comment by younesbelkada** [comment] 2023-03-02 09:38
Thanks everyone for the report! 
There may be a bug! Can you share with us a simple reproducible script? 🙏

**Comment by younesbelkada** [comment] 2023-03-02 09:47
@Ytlskys it seems that the issue might be related to `numpy` , can you try to upgrade it? (`pip install --upgrade numpy`)
@dengyuning @Ren-Ma I ran the `gpt2-sentiment.py` script with the latest version of `trl` and things seems to work fine! What version of `trl` are you using?

**Comment by Ytlskys** [comment] 2023-03-02 13:45
@younesbelkada @Ren-Ma Thank you very much. I successfully solved this issue after using @Ren-Ma your method, but I got the same problem with @dengyuning  later,I tried to upgrade the package and ran it successfully.Thanks again！

**Comment by dengyuning** [comment] 2023-03-03 07:01
> @younesbelkada @Ren-Ma Thank you very much. I successfully solved this issue after using @Ren-Ma your method, but I got the same problem with @dengyuning later,I tried to upgrade the package and ran it successfully.Thanks again！

Can you tell me your environment? I am using `trl 0.2.2.dev0, transformers 4.22.1, datasets 2.4.0, torch 1.10.0, numpy 1.21.2 tensorflow 2.9.1` and the job failed.

**Comment by Ytlskys** [comment] 2023-03-03 07:35
trl  0.3.1，transformers  4.26.1，datasets 2.0.0，torch  1.12.1+cu116，tensorflow-gpu 2.10.0，numpy 1.23.4

**Comment by younesbelkada** [comment] 2023-03-03 08:23
@dengyuning can you trying upgrading your `torch` package?

**Comment by dengyuning** [comment] 2023-03-03 08:36
> @dengyuning can you trying upgrading your `torch` package?

Yeah I think it has something to do with `torch`. I can only use `torch 1.10`. It does not support torch.sum(axis=None). 
![7e8b6ca4d819d882daf547b54bea8c8](https://user-images.githubusercontent.com/23352752/222671143-65585814-e6f2-424b-938b-930dfe283e44.png)

I changed the code in core.py :
![image](https://user-images.githubusercontent.com/23352752/222671703-1aa6678c-9cef-4e53-ac4a-dda52191f7ca.png)
to 
![image](https://user-images.githubusercontent.com/23352752/222671926-ca06e3d5-657f-41d4-9dde-f92219942ed6.png)

and it works now.

**Comment by younesbelkada** [comment] 2023-03-03 09:34
Thanks so much @dengyuning for digging further! 
I believe this can be upstreamed in https://github.com/lvwerra/trl/pull/190 ! Again thanks for this finding!

**Comment by lvwerra** [comment] 2023-03-06 13:58
Closing this as #190 got merged. Feel free to reopen if the issue persists.

**Closed by lvwerra** 2023-03-06 13:58 UTC
