### ISSUE TITLE
SFT Trainer to reproduce Stanford Alpaca 

### ISSUE THREAD

**Issue by Lyken17** [lvwerra/trl#439] opened 2023-06-15 16:48 UTC
Love the simplicity of the framework and I would like to try to re-write [stanford alpaca](https://github.com/tatsu-lab/stanford_alpaca) in TRL.

While I follow prompting style in alpaca,  I notice two issues that blocks my progress

1. How to mask answers during instruction tuining? Current SFTrainer does not seem to provide such a function / example. (mentioned in https://github.com/lvwerra/trl/issues/426#issuecomment-1589799595 as well)
2. What does SFTrainer differ from HF original trainer during the training loop? For example, the follow code snippet returns error on OPT model forward which is weired and bit confusing

```python
from datasets import load_dataset
from trl import SFTTrainer
import transformers

dataset = load_dataset("tatsu-lab/alpaca", split="train")

model = transformers.AutoModelForCausalLM.from_pretrained("facebook/opt-350m")
tokenizer = transformers.AutoTokenizer.from_pretrained("facebook/opt-350m")

def formatting_prompts_func(example):
    if len(example["input"]) >= 2:
        text = f'''Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
        
        ### Instruction:
        {example['instruction']}
        
        ### Input:
        {example['input']}
        
        ### Response:
        {example['output']}
        '''
    else:
        text = f'''Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
        
        ### Instruction:
        {example['instruction']}
        
        ### Response:
        {example['output']}
        '''
    return text

trainer = SFTTrainer(
    model,
    train_dataset=dataset,
    formatting_func=formatting_prompts_func,
    max_seq_length=512,
)

trainer.train()

```

```bash
│ /home/ligeng/anaconda3/envs/alpaca/lib/python3.10/site-packages/transformers/models/opt/modeling │
│ _opt.py:639 in forward                                                                           │
│                                                                                                  │
│    636 │   │   if inputs_embeds is None:                                                         │
│    637 │   │   │   inputs_embeds = self.embed_tokens(input_ids)                                  │
│    638 │   │                                                                                     │
│ ❱  639 │   │   batch_size, seq_length = input_shape                                              │
│    640 │   │   past_key_values_length = past_key_values[0][0].shape[2] if past_key_values is no  │
│    641 │   │   # required mask seq length can be calculated via length of past                   │
│    642 │   │   mask_seq_length = past_key_values_length + seq_length                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by younesbelkada** [comment] 2023-06-16 16:51
Hi @Lyken17 

Thanks so much for your words and for the handy reproducible snippet.

Indeed, the correct way to use `formatting_func` when you use a non-packed dataset is to make sure that the formatting function properly processes all elements of the examples one by one and returns an array of processed text. 
The shared snippet will work when using it in the context of packed dataset:

```python
from datasets import load_dataset
from trl import SFTTrainer
import transformers

dataset = load_dataset("tatsu-lab/alpaca", split="train")

model = transformers.AutoModelForCausalLM.from_pretrained("facebook/opt-350m")
tokenizer = transformers.AutoTokenizer.from_pretrained("facebook/opt-350m")

def formatting_prompts_func(example):
    if len(example["input"]) >= 2:
        text = f'''Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
        
        ### Instruction:
        {example['instruction']}
        
        ### Input:
        {example['input']}
        
        ### Response:
        {example['output']}
        '''
    else:
        text = f'''Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
        
        ### Instruction:
        {example['instruction']}
        
        ### Response:
        {example['output']}
        '''
    return text

trainer = SFTTrainer(
    model,
    train_dataset=dataset,
    formatting_func=formatting_prompts_func,
    max_seq_length=512,
    packing=True,
)

trainer.train()
```
But will fail in the case you don't use a packed dataset (default behavior). 

For more details, the snippet you shared lead to a silent bug since in the call to `formatting_func(element)` element is in fact a dictionary of arrays - and the array contains each sample of the mini-batch (because we call ` dataset.map(tokenize, batched=True, xx)` under the hood. The fix is to create a formatting function that takes that into account and properly processes all the input and returns an array of texts, only in the case of non-packed dataset. The working final script should be: 

```python
from datasets import load_dataset
from trl import SFTTrainer
import transformers

dataset = load_dataset("tatsu-lab/alpaca", split="train")

model = transformers.AutoModelForCausalLM.from_pretrained("facebook/opt-350m")
tokenizer = transformers.AutoTokenizer.from_pretrained("facebook/opt-350m")

def formatting_prompts_func(examples):
    output_text = []
    for i in range(len(examples["instruction"])):
        instruction = examples["instruction"][i]
        input_text = examples["input"][i]
        response = examples["output"][i]

        if len(input_text) >= 2:
            text = f'''Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
            
            ### Instruction:
            {instruction}
            
            ### Input:
            {input_text}
            
            ### Response:
            {response}
            '''
        else:
            text = f'''Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
            
            ### Instruction:
            {instruction}
            
            ### Response:
            {response}
            '''
        output_text.append(text)

    return output_text

trainer = SFTTrainer(
    model,
    train_dataset=dataset,
    formatting_func=formatting_prompts_func,
    max_seq_length=512,
)

trainer.train()
```

I have also updated the documentation a bit to clarify this point to future users. You can now install TRL from source and you should be able to run the script properly.

Regarding your second question, I suggest we bring up the discussion on the thread you have mentioned and see together how we can add this new data collator to mask the answers, and close this issue to centralize the discussion there. How does that sound to you?

**Comment by younesbelkada** [comment] 2023-06-20 15:53
Hi @Lyken17 
#445 has been merged, I believe you have now all the ingredients to replicate the Stanford alpaca using TRL. We also would love to see it on the official examples of TRL. Would you like to collaborate on that and share your findings here? Thanks!

**Comment by gaetanlop** [comment] 2023-06-20 23:12
Hi @younesbelkada, thanks a lot for adding this DataCollatorForCompletionOnlyLM. If I understand well, it works for datasets like Alpaca with an instruction and a response but not for chat datasets like the Open Assistant one. Is there any planned work on adding a data collator for chat datasets where you only compute the loss for the assistant responses? If not and if it is of interest, I can work on it.

**Comment by younesbelkada** [comment] 2023-06-21 06:34
Hi @gaetanlop 
Thanks so much for your interest, yes we definitely want to add that datacollator and indeed it would be great if you can work on it! 
Feel free to start over the PR and take some inspiration from #445 and ping us (myself, @lvwerra @vwxyzjn) once you need a review. Meanwhile if you have any question please don't hesitate!

**Comment by gaetanlop** [comment] 2023-06-21 11:58
Thanks @younesbelkada  for your response. Will work on this and submit a PR this week.

**Closed** 2023-07-24 15:04 UTC
