### ISSUE TITLE
Repro basic example fails with 'PeftModel' or 'PeftConfig' is not defined even when `peft_config` = None

### ISSUE THREAD

**Issue by w601sxs** [lvwerra/trl#518] opened 2023-07-14 13:21 UTC
## Setup:

Name: trl
Version: 0.4.7

Name: transformers
Version: 4.30.2

Name: torch
Version: 2.0.0

Name: peft
Version: 0.3.0

## Case 1
Trying the basic example from docs:

```
from peft import PeftModel, LoraConfig
from transformers import AutoModelForCausalLM
from datasets import load_dataset
from trl import SFTTrainer

dataset = load_dataset("imdb", split="train")

model = AutoModelForCausalLM.from_pretrained("facebook/opt-350m", device_map='auto')

trainer = SFTTrainer(
    model,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=512,
    peft_config=None
)

trainer.train()
```

### Error

```
Found cached dataset imdb (/home/ec2-user/.cache/huggingface/datasets/imdb/plain_text/1.0.0/d613c88cf8fa3bab83b4ded3713f1f74830d1100e171db75bbddb80b3345c9c0)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[10], line 18
     14 dataset = load_dataset("imdb", split="train")
     16 model = AutoModelForCausalLM.from_pretrained("facebook/opt-350m", device_map='auto')
---> 18 trainer = SFTTrainer(
     19     model,
     20     train_dataset=dataset,
     21     dataset_text_field="text",
     22     max_seq_length=512,
     23     peft_config=None
     24 )
     26 trainer.train()

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:147, in SFTTrainer.__init__(self, model, args, data_collator, train_dataset, eval_dataset, tokenizer, model_init, compute_metrics, callbacks, optimizers, preprocess_logits_for_metrics, peft_config, dataset_text_field, packing, formatting_func, max_seq_length, infinite, num_of_sequences, chars_per_token)
    145     if callbacks is None:
    146         callbacks = [PeftSavingCallback]
--> 147 elif not isinstance(model, (PreTrainedModel, PeftModel)):
    148     model = AutoModelForCausalLM.from_pretrained(model)
    150 if tokenizer is None:

NameError: name 'PeftModel' is not defined
```

## Case 2
If I explicitly pass in a `PeftConfig`:

```
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

dataset = load_dataset("imdb", split="train")

model = AutoModelForCausalLM.from_pretrained("facebook/opt-350m", device_map='auto')

trainer = SFTTrainer(
    model,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=512,
    peft_config=peft_config
)

trainer.train()
```

### Error
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[11], line 18
     14 dataset = load_dataset("imdb", split="train")
     16 model = AutoModelForCausalLM.from_pretrained("facebook/opt-350m", device_map='auto')
---> 18 trainer = SFTTrainer(
     19     model,
     20     train_dataset=dataset,
     21     dataset_text_field="text",
     22     max_seq_length=512,
     23     peft_config=peft_config
     24 )
     26 trainer.train()

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:128, in SFTTrainer.__init__(self, model, args, data_collator, train_dataset, eval_dataset, tokenizer, model_init, compute_metrics, callbacks, optimizers, preprocess_logits_for_metrics, peft_config, dataset_text_field, packing, formatting_func, max_seq_length, infinite, num_of_sequences, chars_per_token)
    123     raise ValueError(
    124         "You passed a `DataCollatorForCompletionOnlyLM` to the SFTTrainer. This is not compatible with the `packing` argument."
    125     )
    127 if is_peft_available() and peft_config is not None:
--> 128     if not isinstance(peft_config, PeftConfig):
    129         raise ValueError(
    130             "If you want to use the PeftModel, you need to pass a PeftConfig object to the SFTTrainer."
    131             f" and you passed a {type(peft_config)}."
    132         )
    134     if not isinstance(model, PeftModel):

NameError: name 'PeftConfig' is not defined
```

**Comment by younesbelkada** [comment] 2023-07-14 14:27
Hi @w601sxs 
Thanks for the issue, unfortunately I am not able to reproduce with the main branch of trl. I suspect something might be broken with your PEFT package as SFTTrainer should correctly import the `PeftConfig` and `PeftModel` objects

```python
if is_peft_available():
    from peft import PeftConfig, PeftModel, get_peft_model, prepare_model_for_int8_training
```

Can you uninstall PEFT & re-install it for example from source 
```bash
pip uninstall peft
pip install git+https://github.com/huggingface/peft.git
```
And see if it works?

**Comment by PaulConyngham** [comment] 2023-07-25 13:36
I get the same error trying to run this on colabs:

https://i.postimg.cc/FRtBCHTK/Screen-Shot-2023-07-25-at-11-34-21-pm.png

&

https://i.postimg.cc/Yq2ysVzQ/Screen-Shot-2023-07-25-at-11-34-31-pm.png

**Comment by PaulConyngham** [comment] 2023-07-26 03:12
@w601sxs would you mind taking a look?

**Comment by PaulConyngham** [comment] 2023-07-26 07:02
I ran this command on colabs

```
!pip uninstall peft
!pip install git+https://github.com/huggingface/peft.git
```

 Even after installing trl, colabs provided the following warning:
 
 ```
 WARNING: Skipping peft as it is not installed.
 ```
 
 Unfortunately even after fixing this it did not fix the error executing this code block
 
 ```
 from datasets import load_dataset
from trl import SFTTrainer

dataset = load_dataset("imdb", split="train")

trainer = SFTTrainer(
    "facebook/opt-350m",
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=512,
)
trainer.train()
```
Produced the following error:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-4-cec9f6318251>](https://localhost:8080/#) in <cell line: 6>()
      4 dataset = load_dataset("imdb", split="train")
      5 
----> 6 trainer = SFTTrainer(
      7     "facebook/opt-350m",
      8     train_dataset=dataset,

[/usr/local/lib/python3.10/dist-packages/trl/trainer/sft_trainer.py](https://localhost:8080/#) in __init__(self, model, args, data_collator, train_dataset, eval_dataset, tokenizer, model_init, compute_metrics, callbacks, optimizers, preprocess_logits_for_metrics, peft_config, dataset_text_field, packing, formatting_func, max_seq_length, infinite, num_of_sequences, chars_per_token)
    145             if callbacks is None:
    146                 callbacks = [PeftSavingCallback]
--> 147         elif not isinstance(model, (PreTrainedModel, PeftModel)):
    148             model = AutoModelForCausalLM.from_pretrained(model)
    149 

NameError: name 'PeftModel' is not defined
```

**Comment by JiaxinQin0814** [comment] 2023-07-26 09:35
I met the same problem

**Comment by younesbelkada** [comment] 2023-07-27 12:20
Hmmmm hard to know like that, I really suspect your peft installation is broken. Can you perhaps try with a fresh new enviornement ?

**Comment by PaulConyngham** [comment] 2023-07-28 03:49
I restarted the env, installed TRL, and reinstalled PEFT as per your instructions @younesbelkada.

Here is a colabs notebook for you to replicate it yourself:

https://colab.research.google.com/drive/1JrfnmcgKztl1fxyvunw0oik_Q-FwJwRu?usp=sharing

screenshot replicating the error:

<img width="945" alt="Screen Shot 2023-07-28 at 1 48 17 pm" src="https://github.com/lvwerra/trl/assets/10569375/9764bf3a-2351-4438-9924-94f7c3780b11">

**Comment by younesbelkada** [comment] 2023-07-28 07:40
Thanks for sharing the notebook @PaulConyngham  
Strangely, in my case I get an OOM issue, meaning it passed that line correctly:

```bash
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py](https://localhost:8080/#) in forward(self, input, target)
   1172 
   1173     def forward(self, input: Tensor, target: Tensor) -> Tensor:
-> 1174         return F.cross_entropy(input, target, weight=self.weight,
   1175                                ignore_index=self.ignore_index, reduction=self.reduction,
   1176                                label_smoothing=self.label_smoothing)

[/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py](https://localhost:8080/#) in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction, label_smoothing)
   3027     if size_average is not None or reduce is not None:
   3028         reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 3029     return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
   3030 
   3031 

OutOfMemoryError: CUDA out of memory. Tried to allocate 784.00 MiB (GPU 0; 14.75 GiB total capacity; 13.50 GiB already allocated; 134.81 MiB free; 13.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by PaulConyngham** [comment] 2023-07-29 00:23
@younesbelkada  it is going out of memory because of the free tier T4 under the hood. 

It is not passing that line when you use a runtime with: V100 with High ram.

Also, why is the opt-350m, 350m parameter model OOMing a T4?

**Comment by PaulConyngham** [comment] 2023-07-29 00:40
Super bizzare @younesbelkada. Running it today there is no error. Has there been updates to Peft or Trl?

**Comment by younesbelkada** [comment] 2023-07-31 10:58
Hmmm, the latest PEFT update was around last week .. 
Glad that now it worked but I think weird something used to happen on your previous enviornment 
Closing this issue for now, feel free to re-open if you think that this has not been addressed

**Closed by younesbelkada** 2023-07-31 10:58 UTC

**Comment by tigerinus** [comment] 2023-08-10 08:03
Seeing the same issue here. Not sure what's the solution from the discussion above....

**Comment by lvwerra** [comment] 2023-08-10 08:11
Have you tried updating PEFT + TRL?
