### ISSUE TITLE
Could not find response key, But there are related keys in IDS

### ISSUE THREAD

**Issue by 1518630367** [lvwerra/trl#588] opened 2023-07-28 11:57 UTC
RuntimeError: Could not find response key [396, 673, 29901] in token IDs tensor([ 
         -100,     1,   673,   278,  1494,  2999,  7348,  1139,   491,  6820,
          278,  1556,  8210,  2933, 29889,   673,   881,   367,   697,  4249,
          518, 29909, 29892,   350, 29892,   315, 29892,   360, 29892,   382,
        29962,    13,    13, 16492, 29901,  1128,  1784, 10901, 11195,  1188,
         1140,   293,  1298,  6471,   526,   727,   297,  2211, 29899, 12531,
         2913, 29973,    13, 29871,    13,   319, 29897, 29871, 29955,    13,
           13,   350, 29897, 29871, 29941, 29906,    13,    13,   315, 29897,
        29871, 29896, 29946,    13,    13,   360, 29897, 29871, 29945,    13,
           13,   382, 29897, 29871, 29906, 29955,    13, 29871,    13,   **396,
          673, 29901**, 29871, 29941, 29906])

**Comment by 1518630367** [comment] 2023-07-28 12:13
The code:
supervised_finetuning_trainer = SFTTrainer(
    base_model,
    train_dataset=data["train"],
    args=training_args,
    tokenizer=tokenizer,
    peft_config=qlora_config,
    dataset_text_field="text",
    max_seq_length=2048,
    data_collator=DataCollatorForCompletionOnlyLM(tokenizer=tokenizer, 
                                                  response_template="# Answer:")
)

**Comment by lvwerra** [comment] 2023-07-28 12:15
Can you provide the full script? To me it looks like your `text` field is already tokenized but it should be raw text.

**Comment by 1518630367** [comment] 2023-07-28 12:32
This is my  full script .

> Can you provide the full script? To me it looks like your `text` field is already tokenized but it should be raw text.

Yes, This is my full script

**Comment by tkreiman** [comment] 2023-07-30 04:44
I looked through the source code, and it looks like the DataCollatorForCompletionOnlyLM is wrong. The code is currently written:

```
if self.response_token_ids == examples[i]["input_ids"][idx : idx + len(self.response_token_ids)]:
                        response_token_ids_start_idx = idx

                if response_token_ids_start_idx is None:
                    raise RuntimeError(
                        f'Could not find response key {self.response_token_ids} in token IDs {batch["labels"][i]}'
                    )
```

It should instead be something like:

`a = np.array(self.response_token_ids)
                    b = np.array(batch["labels"][i][idx : idx + len(self.response_token_ids)])
                    if (a == b).all():
                        response_token_ids_start_idx = idx

                if response_token_ids_start_idx is None:
                    raise RuntimeError(
                        f'Could not find response key {self.response_token_ids} in token IDs {batch["labels"][i]}'
                    )`

Not sure if I should open a pull request for this.

**Comment by RyujiTamaki** [comment] 2023-07-31 03:21
Hi, @1518630367 ,

I also encountered the issue that you reported. I have proposed a solution in a PR which I believe resolves this issue as it worked in my environment.

Could you please verify whether the problem is resolved by using the revised DataCollatorForCompletionOnlyLM class provided in my PR? I appreciate your help and look forward to your feedback.

Thank you.

**Comment by RyujiTamaki** [comment] 2023-07-31 06:50
I've realized that my corrections were incorrect since the existing unit tests are passing. I will investigate the cause of this.
I've closed this PR. Sorry.

**Comment by RyujiTamaki** [comment] 2023-07-31 09:18
As mentioned in the PR I closed earlier, it seems there is an error in the process within DataCollatorForCompletionOnlyLM. It compares examples[i][“input_ids”] and batch[“labels”][i], but the latter contains values after being padded by the tokenizer, which I think causes the indexes to differ. Notably, this issue appears to occur only when the tokenizer's padding_side is set to "left". This setting leads to padding being added to the start of the sequences, potentially causing misalignment between the "input_ids" and "labels".

test snipet:
```
model_id = “trl-internal-testing/dummy-GPT2-correct-vocab”
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = “left”

response_template = “### Response:\n”
data_collator = DataCollatorForCompletionOnlyLM(response_template, tokenizer=tokenizer, mlm=False)

text1 = “”"\n\n### Instructions:\nHello all this should be masked\n\n### Response:\nI have not been masked correctly.“”"
text2 = “”"\n\n### Instructions:\nThis is another longer text that should also be masked.\n\n### Response:\nThis response has not been masked correctly, but it is significantly longer than the previous one.“”"

encoded_text1 = tokenizer(text1)
encoded_text2 = tokenizer(text2)

examples = [encoded_text1, encoded_text2]
batch = data_collator(examples)
```

output:
```
File ~/Documents/github/trl/trl/trainer/utils.py:101, in DataCollatorForCompletionOnlyLM.torch_call(self, examples)
     98         response_token_ids_start_idx = idx
    100 if response_token_ids_start_idx is None:
--> 101     raise RuntimeError(
    102         f'Could not find response key {self.response_token_ids} in token IDs {batch["labels"][i]}'
    103     )

RuntimeError: Could not find response key [21017, 18261, 25, 198] in token IDs tensor([ -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         -100,  -100,  -100,  -100,  -100,  -100,   198,   198, 21017, 27759,
           25,   198, 15496,   477,   428,   815,   307, 29229,   198,   198,
        21017, 18261,    25,   198,    40,   423,   407,   587, 29229,  9380,
           13])
```

I'll create another Pull Request to fix this issue.

**Comment by RyujiTamaki** [comment] 2023-07-31 09:48
I have submitted another Pull Request.

**Closed** 2023-07-31 12:13 UTC

**Comment by lvwerra** [comment] 2023-08-11 14:49
Should be fixed in #594.

**Comment by aleksanderhan** [comment] 2023-08-27 01:48
I still get the same error

**Comment by skerit** [comment] 2023-12-06 22:26
Thanks @RuntimeRacer, I was just having the same problem. I'm going to try adding a special token.

**Comment by dpecchioli** [comment] 2023-12-14 23:27
Well done ! Thanks @RuntimeRacer! Yes the tokens of a word can change if the word is alone or not!

**Comment by qinchuanhui** [comment] 2024-01-23 16:36
When I do the similar thing, there may also be some context problem when encoding tokens. Just refer to: https://huggingface.co/docs/trl/v0.7.2/en/sft_trainer#using-tokenids-directly-for-responsetemplate

**Comment by kenken6696** [comment] 2024-01-24 10:50
I had the same error and tried special token but in vain.
I solve it to change the padding_side.
`tokenizer.padding_side = "right"`

**Comment by StefansGH** [comment] 2024-01-29 12:49
cant change to padding side ="rigth" with mistral. Bug still persists...

**Comment by StefansGH** [comment] 2024-01-29 12:51
> Should be fixed in #594.

nope. not for right padding

**Comment by deniz-birlikci** [comment] 2024-04-03 01:58
This is still a problem, even with 
`tokenizer.padding_side = "right"`

**Comment by GaganNarula** [comment] 2024-04-17 08:24
My solution was to follow the instruction [here](https://huggingface.co/docs/trl/v0.7.2/en/sft_trainer#using-tokenids-directly-for-responsetemplate)

Basically, I find that the context changes the first token_id of the response template. I was using the "zephyr-7B" model which has the mistral tokenizer.

Solution was to encode first and take the tokens from the second onwards. Padding side doesn't matter, but I kept it to "right"
```
response_template_ids = tokenizer.encode(response_template_string, add_special_tokens=False)[1:]
        
data_collator = DataCollatorForCompletionOnlyLM(
    response_template=response_template_ids,
    tokenizer=tokenizer,
)
```

**Comment by TangJiakai** [comment] 2024-07-09 12:25
> My solution was to follow the instruction [here](https://huggingface.co/docs/trl/v0.7.2/en/sft_trainer#using-tokenids-directly-for-responsetemplate)
> 
> Basically, I find that the context changes the first token_id of the response template. I was using the "zephyr-7B" model which has the mistral tokenizer.
> 
> Solution was to encode first and take the tokens from the second onwards. Padding side doesn't matter, but I kept it to "right"
> 
> ```
> response_template_ids = tokenizer.encode(response_template_string, add_special_tokens=False)[1:]
>         
> data_collator = DataCollatorForCompletionOnlyLM(
>     response_template=response_template_ids,
>     tokenizer=tokenizer,
> )
> ```

However, I used your method and I still encountered the error 
UserWarning: Could not find response key
